title: T615-J Hazmat Drone
barcodetitle: T615-J
favicon: "/assets/img/favicon.png"
social:
  twitter: HazmatDrone
  furaffinity: HazmatDrone
  telegram: HazmatDrone
  github: HazmatDrone
  githubsitesrc: HazmatDrone/HazmatDrone
