# Values that should be consistent across the site
# remote_theme: HazmatDrone/hazcyber1theme

title: HazmatDrone
barcodetitle: T615-J

# Values that pages should be allowed to overwrite easily
defaults:
  -
    scope:
      path: ""
    values:
      favicon: "/assets/img/favicon.png"
      background: "/assets/img/site-bg.png"
      social:
        twitter: ResinDrake
        furaffinity: user/Rubberbutt
        mastodon: "https://rubber.social/@resin"
        telegram: Slatebreaker
        discord: Slatebreaker_Nightwing
        discord_id: 235584007297826819
        github: FERR1TE
        githubsitesrc: "FERR1TE/hazmatdr.one"
      nav:
        - title: Resin
          url: "/resin/"
          icon: "/assets/img/resin-favicon.png"
        - title: FERR1TE
          url: "/FERR1TE/"
          icon: "/assets/img/ferr1te-favicon.png"
        - title: "T615-J"
          url: "/"
          icon: "/assets/img/favicon.png"
        - title: Tekxach
          url: "/tekxach/"
          icon: "/assets/img/tekxach-favicon.png"
        - title: Drakkite
          url: "/drakkite/"
          icon: "/assets/img/drakkite-favicon.png"
