# Values that should be consistent across the site
# remote_theme: HazmatDrone/hazcyber1theme

title: HazmatDrone
barcodetitle: T615-J

# Values that pages should be allowed to overwrite easily
defaults:
  -
    scope:
      path: ""
    values:
      favicon: "/assets/img/favicon.png"
      background: "/assets/img/site-bg.png"
      social:
        twitter: HazmatDrone
        furaffinity: user/HazmatDrone
        mastodon: "https://rubber.social/@resin"
        telegram: HazmatDrone
        discord: 235584007297826819
        github: HazmatDrone
        githubsitesrc: "HazmatDrone/hazmatdr.one"
      nav:
        - title: "T615-J"
          url: "/"
          icon: "/assets/img/favicon.png"
        - title: Resin
          url: "/resin/"
          icon: "/assets/img/resin-favicon.png"
        - title: Tekxach
          url: "/tekxach/"
          icon: "/assets/img/tekxach-favicon.png"
        - title: Drakkite
          url: "/drakkite/"
          icon: "/assets/img/drakkite-favicon.png"
