# Values that should be consistent across the site
title: T615-J Hazmat Drone
barcodetitle: T615-J

# Values that pages should be allowed to overwrite easily
defaults:
  -
    scope:
      path: ""
    values:
      favicon: "/assets/img/favicon.png"
      social:
        twitter: HazmatDrone
        furaffinity: user/HazmatDrone
        telegram: HazmatDrone
        github: HazmatDrone
        githubsitesrc: HazmatDrone/HazmatDrone
      nav:
        - title: T615-J
          url: "/"
        - title: Tekxach:
          url: "/tekxach"
        - title: Drakkite: 
          url: "/drakkite"
